package com.example.testproject.events

data class EventResponse(
    val end: EventTime,
    val start: EventTime,
    val summary: String,
    val description: String,
    val colorId: Int,
    val location: String,
    val htmlLink: String,
    val reminders: Reminders,
    val guestsCanInviteOthers: Boolean,
    val guestsCanSeeOtherGuests: Boolean,
    val recurrence: List<String>,
    val kind: String,
    val etag: String,
    val id: String,
    val status: String,
    val created: String,
    val updated: String,
    val creator: Creator,
    val organizer: Organizer,
    val iCalUID: String,
    val sequence: Int,
    val eventType: String,
)